### ISSUE TITLE
add :key="index" to all v-for loops

### ISSUE THREAD

**Issue by vinstah** [stormseed/quasar-calendar#18]
I'm using quasar 0.15.10 and by default it uses eslint vue plugin which requires you to have keys for the for loops.

please add keys to the loops in you vue components

Thanks

**Comment by sirbeagle** [comment]
I have this corrected in a dev version - you'll see it here very soon. 😄

**Comment by sirbeagle** [comment]
closed in v0.2.1

**Comment by vinstah** [comment]
still happening there are multiple v-for loops you I see you only updated one v-for on each component

**Comment by sirbeagle** [comment]
I think I may have messed up the master branch - I'm working on a new feature right now and I'm seeing a bunch of errors I know I already fixed. I'll investigate as I'm hoping to push the new feature (and the existing fixes) later on today.
